name: Build

on: push

jobs:
  build:
    if: github.repository_owner == 'bitpatty'
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.4.0'
      - run: npm install
      - run: npm run build
      - run: npm run test
